import type { ActorChatResponse } from "@/lib/education-api";

function downloadBlob(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
}

export function exportEducationMarkdown(data: ActorChatResponse, displayText: string) {
  const title =
    data.export?.title ||
    [data.board, data.subject, data.topic].filter(Boolean).join(" ") ||
    "education-portal-response";
  const header = `# ${title}\n\n_Generated by Brahmando Education Portal_\n\n`;
  downloadBlob(`${slugify(title) || "questionnaire"}.md`, header + displayText, "text/markdown;charset=utf-8");
}

export function exportEducationJson(data: ActorChatResponse, displayText: string) {
  const title =
    data.export?.title ||
    [data.board, data.subject, data.topic].filter(Boolean).join(" ") ||
    "education-portal-response";
  const payload = {
    title,
    module: data.module,
    exported_at: new Date().toISOString(),
    markdown: displayText,
    ...(data.export ? { structured: data.export } : {}),
    raw: data,
  };
  downloadBlob(`${slugify(title) || "questionnaire"}.json`, JSON.stringify(payload, null, 2), "application/json");
}

export function exportEducationText(data: ActorChatResponse, displayText: string) {
  const title =
    data.export?.title ||
    [data.board, data.subject, data.topic].filter(Boolean).join(" ") ||
    "education-portal-response";
  downloadBlob(`${slugify(title) || "questionnaire"}.txt`, displayText, "text/plain;charset=utf-8");
}
